### ISSUE TITLE
Benchmarks not working for matklad

### ISSUE THREAD

**Issue by matklad** [jgm/djot.js#16]
Ok, I think I've figured that out. `npm run build` produces `./dist`, but not `./lib`. `npx tsc` is the thing which produces `./lib`.

**Comment by matklad** [comment]
I _think_ that's also a reason for https://github.com/jgm/djot.js/issues/10 ?

**Comment by matklad** [comment]
Ok, yeah, indeed. If I clone a repo, and run `npm install -g .` without running tsc manually, I don't get a `djot` cli utility. If I run the `tsc`, I get it. 

So I would hasard a guess that what happens is that thee Makefile on @jgm machine is the thig which invokes tsc and makes the stuff work:

https://github.com/jgm/djot.js/blob/9f6f7168dcc85b87f9b67e7f00b21db6ee553142/Makefile#L7-L8

npm howevere is unaware of Makefile, only does webpack, which then breaks benchmarks and installation.

**Comment by matklad** [comment]
Inb4 "any idea how to fix it": not really, I very carefully designed my software engineer career to mostly avoid npm, webpack and related technologies :D

**Comment by jgm** [comment]
OK, just use `make bench` -- it now runs `tsc` first.
I also fixed `npm run build` so it does both `tsc` and `webpack`.

**Comment by jgm** [comment]
For good measure I'll add tsc to `npm run bench` so you can add the parameter: `npm run bench PATTERN`
