### ISSUE TITLE
Single lines starting with `{a="` disappear

### ISSUE THREAD

**Issue by hellux** [jgm/djot.js#47]
```
{a=" inline text
```
gives no output instead of
```html
<p>{a=&rdquo; inline text</p>
```

**Comment by jgm** [comment]
Interesting, if you add a blank line after it, or something like "# head", you'll get the expected output.
So Perhaps we just need to ensure that the `continue` function is called again at the end of input?

**Comment by jgm** [comment]
We need to handle the case where the `close` method for a attributes container is called, not because `continue` fails, but because the end of the document has been reached.  If at this point the container's `extra.status` is `"continue"`, we need to reparse.
