### ISSUE TITLE
Why entities in html output?

### ISSUE THREAD

**Issue by bdarcus** [jgm/djot.js#50]
Probably a small issue, but for the smart punctuation examples, you output as html entities. Why not just the appropriate unicode characters?

Beside the obvious, one can't process the output as XML:

```console
❯ djot /tmp/test.dj | xmllint -
-:9: parser error : Entity 'hellip' not defined
<p>And now &hellip;</p>
                   ^
-:14: parser error : Entity 'ldquo' not defined
<p>&ldquo;Hello,&rdquo; said the spider.</p>
          ^
-:14: parser error : Entity 'rdquo' not defined
<p>&ldquo;Hello,&rdquo; said the spider.</p>
```

**Comment by jgm** [comment]
Maybe there was a reason, but if so I've forgotten what it was.
