### ISSUE TITLE
Caption parsing is buggy

### ISSUE THREAD

**Issue by matklad** [jgm/djot.js#57]
```djot
| 1 | 2 |

 ^ cap1
 
 ^ cap2
```

Ast:

```
doc
  table
    caption
      str text="cap2"
    caption
      str text="cap1"
    caption
    row head=false
      cell head=false align="default"
        str text="1"
      cell head=false align="default"
        str text="2"
```

Two problems here:

- a dummy extra empty caption
- our [types](https://github.com/jgm/djot.js/blob/2f0bb7ca6991645aef1e8283d1e6e7aa5ad4e796/src/ast.ts#L137) require exactly one caption

**Comment by matklad** [comment]
One thing I've been thinking about is that perhaps, rather than additing captions to the table, we should have

```ts
interface Table extends HasAttributes {
  tag: "table";
  children: Row[];
}

interface Figure extends HasAttributes {
  tag: "figure";
  children: [Block, Caption]
}
```

**Comment by jgm** [comment]
This is how typst is doing it, if I recall correctly.
Captions on code blocks are a common request in pandoc.

**Comment by jgm** [comment]
I think I've fixed the bug. Perhaps the suggestion about generalizing captions could go in a separate issue so we don't lose track.
