### ISSUE TITLE
Clarification around list items

### ISSUE THREAD

**Issue by eanyanwu** [jgm/djot.js#66]
First off, I'd like to appreciate the effort and patience you've put into both common mark and djot 🙏🏽 🙏🏽 

 In trying to understand the syntax better, I ran across what appears to be an inconsistency in nesting block elements inside list items.

[playground link](https://djot.net/playground/?text=1.+list+item%0A++%3E+this+is+not+a+block+quote%0A%0A1.+list+item%0A++%3A%3A%3A%0A++this+is+nota+div%0A++%3A%3A%3A%0A%0A1.+another+list+item%0A++%60%60%60%0A++this+is+a+code+block%3F%0A++%60%60%60&mode=html&sourcepos=false)

- A bracket (i.e. `< `) inside a list item gets rendered literally in html (instead of rendering it as a block quote) 👍🏽 
- Three colons (i.e. `:::`) inside a list item gets rendered literally in html (instead of rending it as a `<div>`) 👍🏽 
- _But three backticks (i.e. ` ``` `)  inside a list item gets rendered as a code block_ 🤔

Is this intentional? If so, can you provide some reasoninng behind it (or a link if this has been brought up before)? I'm just trying to get a feel for the rules

Thanks again!

**Comment by matklad** [comment]
I think you might have pasted a wrong link :)

**Comment by eanyanwu** [comment]
woops, fixed 🤦🏽‍♂️

**Comment by jgm** [comment]
You need a blank line between paragraphs and other block-level elements (block quotes, fenced divs, fenced code).

**Comment by jgm** [comment]
Sorry, I see now that you are asking why you don't need the blank line before fenced code.  Well, you *do* need it before a fenced code *block*.  What you see in the playground is *inline* code (which can be between matched pairs of backticks of any length, including 3).

[Playground](https://djot.net/playground/?text=This+is%0A%60%60%60%0Ainline+code%0A%60%60%60%0Aand%0Athis+is%0A%0A%60%60%60%0Aa+code%0Ablock%0A%60%60%60%60%0A&sourcepos=false)

**Comment by eanyanwu** [comment]
I see, so the difference is that a code block has both an inline and block "form", but the div and blockquote element do not.

Thanks!

**Comment by jgm** [comment]
Just a terminological note: "code block" refers to the block element; we don't use that terminology for inline code.
