### ISSUE TITLE
Add comment in AST

### ISSUE THREAD

**Issue by black-desk** [jgm/djot.js#88]
To use djot.js as a djot formatter, we need to add comments node in AST to keep comments in the output.

**Comment by jgm** [comment]
Well, it's an abstract syntax tree, not a concrete syntax tree, and these usually don't contain comments.

**Comment by jgm** [comment]
@matklad any thoughts on this issue?
See also https://github.com/jgm/djot/issues/67
We will probably revamp comments in some way.

**Comment by matklad** [comment]
This is a design question: 

* Either djot syntax tree is full-fidelity, such that `print . parse = id`
* Or djot sytnax tree only preserves _semantics_: different source code yields the same tree

My gut feeling is that, long term, it is better if you have separate trees and parser -- semantics-preserving AST parser for actual intended use-case (rendering djot documents as html/pdf/etc) and a syntax-preserving parser for tooling. You can do both, but that increases complexity of the implementation, and _also_ increases complexity for the user. 

Eg., if we add comments to djot.js AST, then filters would have to care about commetns. 


IIRC, someone is buildign a tree sitter grammer for djot? I'd probably try to build a formatter on top of that.

**Comment by jgm** [comment]
For the treesitter grammar see https://github.com/jgm/djot/discussions/280

**Comment by AvtechScientific** [comment]
> Well, it's an abstract syntax tree, not a concrete syntax tree, and these usually don't contain comments.

I think a comment is a regular syntactic element it's not a syntactic sugar. The fact that it normally is ignored by compiler causes this false feeling of comment being meaningless.

What's wrong about `{% foo %} => AST => html => <!-- foo -->` ? Just as any other element?...
