### ISSUE TITLE
adjacent lists render incorrectly

### ISSUE THREAD

**Issue by iacore** [jgm/djot.js#91]
try to render this

```
- a
- b

- c

- d
- e
``` 

current result starts with

```
<ul>
<li><p>a</p></li>
```

that's not supposed to happen

## Workaround

```
- a
- b

{}

- c

{}

- d
- e
```

**Comment by jgm** [comment]
> that's not supposed to happen

according to what?

**Comment by iacore** [comment]
o_o

according to my common sense

**Comment by jgm** [comment]
If you like, you can put up an issue on jgm/djot suggesting that the spec be changed.  This repo is for djot.js, which is correctly implementing the current spec...
